### PR TITLE
Enhance BaseReader to allow custom adapters access to instance variables

### PR DESCRIPTION
**Pull request by justHungryMan**
This PR addresses the issue #168 by modifying how the `adapter` is assigned within the `BaseReader` class. By using `MethodType`, we enable custom adapters to access instance variables and methods, enhancing the flexibility and usability of custom adapters.

### Changes Made
- Changed the assignment of `self.adapter` to `MethodType(adapter, self)` if a custom adapter is provided.
- Updated relevant unit tests to reflect this change and ensure functionality.

### Impact
This change allows developers to write more intuitive and robust custom adapters by leveraging the internal state of the `BaseReader` instance, leading to cleaner and more maintainable code.

### Tests
- Added a test case in `tests/pipeline/test_adapter_reader.py` to verify that the custom adapter can access and modify instance variables as expected.

Please review the changes and provide your feedback.

### CODE REVIEW

**Comment by guipenedo** [comment]
Maybe we should also add this to writers' adapters?

**Comment by justHungryMan** [comment]
Do we need test code for writer's adapter?

**Comment by guipenedo** [comment]
No I don't think so

**Comment by guipenedo** [comment]
I added it and also changed the docstrings a bit.
Thanks a lot, great change :)

**Pull request merged**
